# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.3"
    - name: Install pytest and check requirements
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pip install pytest
        pipreqs --force
        pip install -r requirements.txt
    - name: Test all
      run: |
        pytest
  style_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.3"
    - name: Install pycodestyle
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - name: Style check all
      run: |
        pycodestyle *.py
